from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="PaginatedResponseEventSummaryItemsItem")


@_attrs_define
class PaginatedResponseEventSummaryItemsItem:
    """Summary event response for list views

    Attributes:
        created (datetime.datetime): Creation timestamp Example: 2024-01-13T10:30:00Z.
        has_payload (bool): Whether event has payload data Example: True.
        id (int):
        trigger_ref (str): Trigger reference Example: core.webhook.
        rule (int | None | Unset):
        rule_ref (None | str | Unset): Rule reference (if event was generated by a specific rule) Example:
            core.timer_rule.
        source (int | None | Unset):
        source_ref (None | str | Unset): Source reference Example: monitoring.webhook_sensor.
        trigger (int | None | Unset):
    """

    created: datetime.datetime
    has_payload: bool
    id: int
    trigger_ref: str
    rule: int | None | Unset = UNSET
    rule_ref: None | str | Unset = UNSET
    source: int | None | Unset = UNSET
    source_ref: None | str | Unset = UNSET
    trigger: int | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        created = self.created.isoformat()

        has_payload = self.has_payload

        id = self.id

        trigger_ref = self.trigger_ref

        rule: int | None | Unset
        if isinstance(self.rule, Unset):
            rule = UNSET
        else:
            rule = self.rule

        rule_ref: None | str | Unset
        if isinstance(self.rule_ref, Unset):
            rule_ref = UNSET
        else:
            rule_ref = self.rule_ref

        source: int | None | Unset
        if isinstance(self.source, Unset):
            source = UNSET
        else:
            source = self.source

        source_ref: None | str | Unset
        if isinstance(self.source_ref, Unset):
            source_ref = UNSET
        else:
            source_ref = self.source_ref

        trigger: int | None | Unset
        if isinstance(self.trigger, Unset):
            trigger = UNSET
        else:
            trigger = self.trigger

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "created": created,
                "has_payload": has_payload,
                "id": id,
                "trigger_ref": trigger_ref,
            }
        )
        if rule is not UNSET:
            field_dict["rule"] = rule
        if rule_ref is not UNSET:
            field_dict["rule_ref"] = rule_ref
        if source is not UNSET:
            field_dict["source"] = source
        if source_ref is not UNSET:
            field_dict["source_ref"] = source_ref
        if trigger is not UNSET:
            field_dict["trigger"] = trigger

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        created = isoparse(d.pop("created"))

        has_payload = d.pop("has_payload")

        id = d.pop("id")

        trigger_ref = d.pop("trigger_ref")

        def _parse_rule(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        rule = _parse_rule(d.pop("rule", UNSET))

        def _parse_rule_ref(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        rule_ref = _parse_rule_ref(d.pop("rule_ref", UNSET))

        def _parse_source(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        source = _parse_source(d.pop("source", UNSET))

        def _parse_source_ref(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        source_ref = _parse_source_ref(d.pop("source_ref", UNSET))

        def _parse_trigger(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        trigger = _parse_trigger(d.pop("trigger", UNSET))

        paginated_response_event_summary_items_item = cls(
            created=created,
            has_payload=has_payload,
            id=id,
            trigger_ref=trigger_ref,
            rule=rule,
            rule_ref=rule_ref,
            source=source,
            source_ref=source_ref,
            trigger=trigger,
        )

        paginated_response_event_summary_items_item.additional_properties = d
        return paginated_response_event_summary_items_item

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
